version: "3.8"

services:
  jupyter:
    container_name: container1-training-ipynb
    build:
      context: ./container1-training-ipynb
      dockerfile: Dockerfile
    image: multimodal-rag-pipeline-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./container1-training-ipynb:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - chromadb
    restart: unless-stopped

  streamlit:
    container_name: container2-running-py
    build:
      context: ./container2-running-py
      dockerfile: Dockerfile
    image: multimodal-rag-pipeline-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./container2-running-py:/app
    environment:
      - CHROMADB_HOST=chromadb
    env_file:
      - ./container2-running-py/.env
    restart: unless-stopped

  chromadb:
    container_name: container3-chromadb
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - ./container3-chromadb/chroma-data:/chroma/chroma/  # Bind mount for persistent storage
    restart: always

volumes:
  chroma-data:
    driver: local
